language: node_js
node_js:
- stable
script:
  - bash scripts/build.sh
after_success:
  - bash scripts/gendocs.sh
  - bash scripts/genexamples.sh
  - bash scripts/genfull.sh
env:
  global:
  - ENCRYPTION_LABEL: a34ff6591ac8